compile_pkgs: simplify configure command and few other things
In configure command there are two major changes. VERSION_REPO is now
set to new path path that is unfortunately board unspecific but as
only one makes sense in new repository arrangement. Second change is
that we no longer build image builder and SDK. Image builder does not
make sense for use. We use updater to build images (medkits). SDK is at
current state useless. It does not contain anything other then compiler,
libraries are missing.

Second change is primarily done because of next change that is going to
be splitting off compile command to few subcommands and making sure that
we build only packages not anything else.

diff --git a/compile_pkgs b/compile_pkgs
--- a/compile_pkgs
+++ b/compile_pkgs
@@ -19,8 +19,7 @@
 declare -A available_commands
 
 BUILD_DIR="$(pwd)"
-SRC_DIR="$(dirname "$0")"
-SRC_DIR="$(cd "$SRC_DIR"; pwd)"
+SRC_DIR="$(readlink -f "$(dirname "$0")")"
 CMD="${0}"
 OPENWRT_URL="https://git.openwrt.org/openwrt/openwrt.git"
 OPENWRT_BRANCH=master
@@ -29,7 +28,7 @@ EVERYTHING=""
 PERL_DEBUG=""
 SH_DEBUG=""
 MAKE_DEBUG=""
-PUBLISH_BRANCH=""
+PUBLISH_BRANCH="hbs"
 DEPTH="--depth 1"
 FORCE=""
 DEFAULT_STEPS=(
@@ -192,24 +191,11 @@ configure() {
 	echo "CONFIG_DEVEL=y" >> .config
 	echo "CONFIG_CCACHE=y" >> .config
 	echo "CONFIG_DOWNLOAD_FOLDER=$DL_MIRROR" >> .config
-	if [ -n "${PUBLISH_BRANCH}" ]; then
-		echo "CONFIG_VERSION_REPO=\"https://repo.turris.cz/${TARGET_BOARD}-${PUBLISH_BRANCH}\"" >> .config
-	else
-		echo "CONFIG_VERSION_REPO=\"https://repo.turris.cz/${TARGET_BOARD}\"" >> .config
-	fi
+	echo "CONFIG_VERSION_DIST=TurrisOS"
+	echo "CONFIG_VERSION_REPO=\"https://repo.turris.cz/${PUBLISH_BRANCH}\"" >> .config
 	echo "CONFIG_VERSION_NUMBER=\"$(_get_version)\"" >> .config
-	if [ "$EVERYTHING" = yes ]; then
-		echo "CONFIG_ALL_KMODS=y" >> .config
-		echo "CONFIG_ALL=y" >> .config
-		echo "CONFIG_IB=y" >> .config
-		echo "CONFIG_IB_STANDALONE=y" >> .config
-		echo "CONFIG_SDK=y" >> .config
-	else
-		echo "CONFIG_ALL=n" >> .config
-		echo "CONFIG_IB=n" >> .config
-		echo "CONFIG_IB_STANDALONE=n" >> .config
-		echo "CONFIG_SDK=n" >> .config
-	fi
+	echo -n "CONFIG_ALL_KMODS=" >> .config
+	[ "$EVERYTHING" = yes ] && echo y || echo n >> .config
 	make $MAKE_DEBUG defconfig
 	OPENWRT_ARCH="$(sed -n 's|^CONFIG_TARGET_BOARD="\([^"]*\)"|\1|p' .config)"
 	EXTRA_KERNEL="$(cat "${SRC_DIR}"/configs/common/* "${SRC_DIR}/configs/${TARGET_BOARD}"/* | sed -n 's|^[[:blank:]]*CONFIG_KERNEL|CONFIG|p')"
@@ -542,20 +528,21 @@ _set_target() {
 }
 
 print_help() {
-	echo "Usage: $CMD [option].. [command].."
+	echo "Usage: $CMD [OPTION].. [COMMAND].."
+	echo "Compile TurrisOS packages. This script fetches, patches and configures OpenWRT tree."
 	echo
 	echo "Available options are:"
-	echo "	-x		Enable debug mode"
 	echo "	-e		Build everything, not just minimal set"
-	echo "	-f[num]		Try hard to get stuff to compile (optional number specifies number of tries)"
+	echo "	-f[NUM]		Try hard to get stuff to compile (optional number specifies number of tries)"
+	echo "	-t BOARD	Set target board to BOARD. This is required for almost all commands."
+	echo "	-b BRANCH	Branch to checkout in OpenWRT. You can optionaly use here any valid git reference in OpenWRT git tree."
+	echo "	-p BRANCH	Name of the branch that is being build. If not specified 'hbs' is used."
+	echo "	-a ARG		Add build arguments - passed directly to make. This option can be specified multiple times."
+	echo "	-l		Do not update local git mirrors. Use them as they are to fetch OpenWRT and its feeds."
+	echo "	-s key		Sign packges with given private key. Key has to be generated using using tool."
 	echo "	-d		Do not use shallow checkouts"
-	echo "	-t board	Set target board to _board_"
-	echo "	-a \"arg1 arg2\"	Set build arguments - passed directly to make"
-	echo "	-b branch	Branch to checkout"
-	echo "	-p branch	Name of the branch that is being build"
-	echo "	-l		Do not update local git mirrors"
-	echo "	-s key		Sign packges with given key"
-	echo "	-h		Show help"
+	echo "	-x		Enable debug mode"
+	echo "	-h, --help	Show this help text"
 	echo
 	echo "Available commands are:"
 	for cmd in "${!available_commands[@]}"; do
@@ -570,18 +557,8 @@ steps=()
 # Parse arguments
 while [ $# -gt 0 ]; do
 	case "$1" in
-		-h|--help)
-			print_help
-			exit 0
-			;;
-		-x)
-			_enable_debug
-			;;
 		-e)
 			EVERYTHING="yes"
-			;;
-		-d)
-			DEPTH=""
 			;;
 		-f*)
 			FORCE="${1#-f}"
@@ -610,6 +587,16 @@ while [ $# -gt 0 ]; do
 		-s)
 			shift
 			BUILD_ARGS="$BUILD_ARGS BUILD_KEY=$1"
+			;;
+		-d)
+			DEPTH=""
+			;;
+		-x)
+			_enable_debug
+			;;
+		-h|--help)
+			print_help
+			exit 0
 			;;
 		*)
 			[ -n "${available_commands[$1]}" ] || \
